# -*- coding: utf-8 -*-
"""Outliers_ML_Escalation_Transition_Engine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZsQNAlDaeRaF0gkC-b4xp_QCgvyoyCKC
"""

STATES = [
    "NORMAL",        # No immediate risk
    "WATCH",         # Monitor situation
    "PREPAREDNESS",  # Prepare resources
    "CRISIS"         # Active emergency
]

def escalation_engine(
    flood_risk_percentage,
    severity_level,
    risk_trend="stable"
):
    state = "NORMAL"
    reason = ""

    # Flood-driven escalation ONLY
    if flood_risk_percentage < 20:
        state = "NORMAL"
        reason = "Low flood risk"

    elif 20 <= flood_risk_percentage < 40:
        state = "WATCH"
        reason = "Moderate flood risk"

    elif 40 <= flood_risk_percentage < 60:
        state = "PREPAREDNESS"
        reason = "High flood risk, preparing"

    elif flood_risk_percentage >= 60:
        state = "CRISIS"
        reason = "Severe flood risk"

    # Crisis-driven escalation (independent of flood)
    if severity_level == "High":
        state = "CRISIS"
        reason = "High severity incident detected"

    return {
        "current_state": state,
        "reason": reason,
        "flood_risk_percentage": flood_risk_percentage,
        "incident_severity": severity_level
    }

escalation_engine(
    flood_risk_percentage=10,
    severity_level="Low"
)

escalation_engine(
    flood_risk_percentage=45,
    severity_level="Medium"
)

escalation_engine(
    flood_risk_percentage=55,
    severity_level="High"
)

escalation_engine(
    flood_risk_percentage=35,
    severity_level="Medium",
    risk_trend="rapid"
)

